name: Save and Restore Build State

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Project
      run: |
        mkdir -p ./build/state
        # Comando para gerar arquivos de build
        echo "Build Completed" > ./build/state/build.log

    - name: Save Build State
      uses: actions/upload-artifact@v4
      with:
        name: build-state
        path: ./build/state

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore Build State
      uses: actions/download-artifact@v4
      with:
        name: build-state
        path: ./build/state

    - name: Run Tests
      run: |
        cat ./build/state/build.log
        # Comando para rodar testes
