name: EXE Build and Deployment

on:
  # Runs on push to any of the below branches
  push:
    branches: 
      - master
      - main
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches: 
      - master
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "exe"
  cancel-in-progress: false

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Flet Build EXE
      run: |
        flet pack main.py --output dist/main.exe

    - name: Upload EXE Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: exe-build-artifact
        path: dist/main.exe

  deploy:
    needs: build  # wait for the "build" job to get done before executing this "deploy" job

    runs-on: windows-latest

    permissions:
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # deploy only on push
        id: deployment
        uses: actions/upload-artifact@v3
        with:
          name: main-exe
          path: dist/main.exe
