name: Build EXE with Flet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Substitua pela versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade flet

    - name: Build EXE with Flet
      run: flet pack main.py --output dist/main.exe

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: main-exe
        path: dist/main.exe
