name: Build EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Permissão para criar releases e upload de arquivos

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pyinstaller
        pip install -r requirements.txt

    - name: Build EXE
      run: pyinstaller --onefile main.py

    - name: Compress Build Output
      run: |
        Compress-Archive -Path dist/* -DestinationPath windows-main-artifact.zip



    - name: Get Current Date
      id: get_date
      run: echo "TAG_NAME=$(date '+%d-%m-%Y-%H-%M')" >> $GITHUB_ENV


    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'aasda1' 
        release_name: 'Build EXE Release - '
        body: |
          Lançamento do executável gerado - .
        draft: false
        prerelease: false

    - name: Upload Windows Artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: windows-main-artifact.zip
        asset_name: windows-main-artifact-.zip
        asset_content_type: application/zip
