name: Build EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'  # Substitua pelo seu Python necessário

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --windowed main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: main-exe
        path: dist/main.exe
