name: Separated Jobs Workflow

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Build Windows
      run: |
        echo "Building for Windows"

  test:
    runs-on: ubuntu-latest
    needs: build-windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Tests
      run: |
        echo "Running Tests"
